# Generated by Django 4.2.4 on 2024-04-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discount_precentage',
            new_name='discount_percentage',
        ),
    ]
