# Generated by Django 4.2.4 on 2024-05-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_discount_precentage_item_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
