# Generated by Django 4.2.4 on 2024-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_item_price_alter_itemimage_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
