# Generated by Django 4.2.4 on 2024-05-11 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
