# Generated by Django 4.2.4 on 2024-05-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_orderhistory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
