# Generated by Django 4.2.4 on 2024-05-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_orderhistory_color_orderhistory_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed')], max_length=255, null=True),
        ),
    ]
