# Generated by Django 4.2.4 on 2024-05-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_orderhistory_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='order_status',
            new_name='status',
        ),
    ]
