# Generated by Django 4.2.4 on 2024-05-17 14:23

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_orderhistory_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='order_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], max_length=255, null=True),
        ),
    ]
