# Generated by Django 4.2.4 on 2024-08-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_order_status_orderhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending')], max_length=255, null=True),
        ),
    ]
