# Generated by Django 5.1.2 on 2024-10-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_orderhistory_order_date_alter_orderhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], max_length=255, null=True),
        ),
    ]
